@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Gustavo Lima",
	"cpf": "121.326.518-308",
	"password": "12345236",
	"role": "ENTREGADOR"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"cpf": "442.326.518-3",
	"password": "12345236"
}

###

# @name update_account
PUT {{baseUrl}}/accounts/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "cinzinha2"
}


// gerando token cod 15